version: "3.9"

services:
  transcripto_api:
    build: .
    container_name: transcripto_server
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./db_dump.sql:/app/db_dump.sql
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000
             --log-config app/core/logging_config.yaml
             --access-log /app/logs/access.log"
  nginx:
    image: nginx:alpine
    container_name: transcripto_router
    ports:
      - "80:80"
    volumes:
      # Use the absolute path to your project
      - /home/eidankhan/transcripto.dev/transcripto-server/frontend:/usr/share/nginx/html:ro,Z
      - /home/eidankhan/transcripto.dev/transcripto-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
    depends_on:
      - transcripto_api